### ISSUE TITLE
Variable ansible_env.ANSIBLE_CONTAINER is undefined

### ISSUE THREAD

**Issue by hackermd** [ansible/ansible-container#596]
##### ISSUE TYPE

Bug Report

##### container.yml 

```yaml
version: "2"

settings:
  conductor_base: tissuemaps/base

services:
  bar:
    from: tissuemaps/base
    roles:
      - role: foo
```

##### roles/foo/tasks/main.yml
```yaml
- debug: msg={{ ansible_env.ANSIBLE_CONTAINER }}
``` 

##### OS / ENVIRONMENT

```

Ansible Container, version 0.9.1
Darwin, MacBook-Pro-4.local, 14.5.0, Darwin Kernel Version 14.5.0: Tue Apr 11 16:12:42 PDT 2017; root:xnu-2782.50.9.2.3~1/RELEASE_X86_64, x86_64
2.7.11 (default, Jan 22 2016, 08:28:37)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] /Users/mdh/Envs/deploy/bin/python2.7
{
  "ContainersPaused": 0,
  "Labels": null,
  "CgroupDriver": "cgroupfs",
  "ContainersRunning": 1,
  "ContainerdCommit": {
    "Expected": "4ab9917febca54791c5f071a9d1f404867857fcc",
    "ID": "4ab9917febca54791c5f071a9d1f404867857fcc"
  },
  "InitBinary": "docker-init",
  "NGoroutines": 43,
  "Swarm": {
    "Managers": 0,
    "ControlAvailable": false,
    "NodeID": "",
    "Cluster": {
      "Spec": {
        "TaskDefaults": {},
        "Orchestration": {},
        "EncryptionConfig": {
          "AutoLockManagers": false
        },
        "Raft": {
          "HeartbeatTick": 0,
          "ElectionTick": 0
        },
        "CAConfig": {},
        "Dispatcher": {}
      },
      "Version": {},
      "ID": "",
      "CreatedAt": "0001-01-01T00:00:00Z",
      "UpdatedAt": "0001-01-01T00:00:00Z"
    },
    "Nodes": 0,
    "Error": "",
    "RemoteManagers": null,
    "LocalNodeState": "inactive",
    "NodeAddr": ""
  },
  "LoggingDriver": "json-file",
  "OSType": "linux",
  "HttpProxy": "",
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "DriverStatus": [
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Supports d_type",
      "true"
    ],
    [
      "Native Overlay Diff",
      "true"
    ]
  ],
  "OperatingSystem": "Alpine Linux v3.5",
  "Containers": 1,
  "HttpsProxy": "",
  "BridgeNfIp6tables": true,
  "MemTotal": 6246776832,
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ],
  "Driver": "overlay2",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "ClusterStore": "",
  "InitCommit": {
    "Expected": "949e6fa",
    "ID": "949e6fa"
  },
  "Isolation": "",
  "SystemStatus": null,
  "OomKillDisable": true,
  "ClusterAdvertise": "",
  "SystemTime": "2017-06-10T14:14:07.328417937Z",
  "Name": "moby",
  "CPUSet": true,
  "RegistryConfig": {
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ],
    "IndexConfigs": {
      "docker.io": {
        "Official": true,
        "Name": "docker.io",
        "Secure": true,
        "Mirrors": null
      }
    },
    "Mirrors": []
  },
  "DefaultRuntime": "runc",
  "ContainersStopped": 0,
  "NCPU": 4,
  "NFd": 26,
  "Architecture": "x86_64",
  "KernelMemory": true,
  "CpuCfsQuota": true,
  "Debug": true,
  "ID": "KC7E:MCGC:TNHP:LBMN:ZPX7:F6AB:OIVT:7P4L:O3QX:5UOJ:C6MQ:YT45",
  "IPv4Forwarding": true,
  "KernelVersion": "4.9.27-moby",
  "BridgeNfIptables": true,
  "NoProxy": "*.local, 169.254/16",
  "LiveRestoreEnabled": false,
  "ServerVersion": "17.03.1-ce",
  "CpuCfsPeriod": true,
  "ExperimentalBuild": false,
  "MemoryLimit": true,
  "SwapLimit": true,
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": null
  },
  "Images": 6,
  "DockerRootDir": "/var/lib/docker",
  "NEventsListener": 1,
  "CPUShares": true,
  "RuncCommit": {
    "Expected": "54296cf40ad8143b62dbcaa1d90e520a2136ddfe",
    "ID": "54296cf40ad8143b62dbcaa1d90e520a2136ddfe"
  }
}
{
  "KernelVersion": "4.9.27-moby",
  "Arch": "amd64",
  "BuildTime": "2017-03-24T00:00:50.070226199+00:00",
  "ApiVersion": "1.27",
  "Version": "17.03.1-ce",
  "MinAPIVersion": "1.12",
  "GitCommit": "c6d412e",
  "Os": "linux",
  "GoVersion": "go1.7.5"
}
```
##### SUMMARY

The `ansible_env.ANSIBLE_CONTAINER` variable is not defined.

##### STEPS TO REPRODUCE

```
ansible-container --debug build --roles-path roles --no-cache
```

##### EXPECTED RESULTS

I would have expected that the variable `ansible_env.ANSIBLE_CONTAINER` would be defined as described in #222. This also used to work with ansible-container versions < 0.4.

##### ACTUAL RESULTS

```
TASK [foo : debug] *************************************************************
task path: /private/tmp/test/roles/foo/tasks/main.yml:2
fatal: [bar]: FAILED! => {
    "failed": true,
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'ANSIBLE_CONTAINER'\n\nThe error appears to have been in '/private/tmp/test/roles/foo/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- debug: msg={{ ansible_env.ANSIBLE_CONTAINER }}\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n - \"{{ foo }}\"\n"
}
```

**Comment by borisno2** [comment]
Not sure if it relates but I noticed this issue after I logged #599

**Comment by j00bar** [comment]
Thank you for reporting this! Would you mind running `docker inspect` on the built Conductor image please?

**Comment by chouseknecht** [comment]
Testing in my environment with 0.9.1, I get the following:

```
TASK [say_hello : Show ANSIBLE_CONTAINER] **************************************
task path: /Users/chouseknecht/projects/roles/say_hello/tasks/main.yml:4
ok: [web] => {
    "ansible_env.ANSIBLE_CONTAINER": "VARIABLE IS NOT DEFINED!"
}
```

The actual task in my role is the following:

```
- name: Show ANSIBLE_CONTAINER
  debug: var=ansible_env.ANSIBLE_CONTAINER
```

That leads me to believe that the ANSIBLE_CONTAINER variable is not being added to the target container.

I can see that it is clearly part of the conductor image, which I just built. Here's from the inspection of that image:

```
"Config": {
            "Hostname": "8682294b9464",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "ANSIBLE_CONTAINER=1"
            ],
```

**Comment by hackermd** [comment]
@chouseknecht thanks for adding further details! Didn't yet manage to work on this.

**Comment by chouseknecht** [comment]
With PR #624, the task from my example above now yields the expected result:

```
TASK [say_hello : Show ANSIBLE_CONTAINER] **************************************
task path: /Users/chouseknecht/projects/roles/say_hello/tasks/main.yml:4
ok: [web] => {
    "ansible_env.ANSIBLE_CONTAINER": "1"
}
```
